### ISSUE TITLE
NoSuchMethodError io.netty.util.internal.PlatformDependent.newAtomicIntegerFieldUpdater

### ISSUE THREAD

**Issue by mfirry** [kamon-io/kamon-influxdb#11]
Hi,
I'm trying `kamon-akka` with `kamon-influxdb` (both `0.6.7`) with `akka` `2.4.16` and I'm getting this error at startup.

What could I be missing?

```
Uncaught error from thread [kamon-akka.actor.default-dispatcher-4] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[kamon]
java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.newAtomicIntegerFieldUpdater(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/concurrent/atomic/AtomicIntegerFieldUpdater;
	at org.asynchttpclient.netty.NettyResponseFuture.<clinit>(NettyResponseFuture.java:52)
	at org.asynchttpclient.netty.request.NettyRequestSender.newNettyResponseFuture(NettyRequestSender.java:311)
	at org.asynchttpclient.netty.request.NettyRequestSender.newNettyRequestAndResponseFuture(NettyRequestSender.java:193)
	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:129)
	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:107)
	at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:216)
	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:184)
	at org.asynchttpclient.BoundRequestBuilder.execute(BoundRequestBuilder.java:35)
	at kamon.influxdb.AsyncHttpClient.post(InfluxDBClient.scala:38)
```

**Comment by dpsoft** [comment]
Hi,
Try with kamon-influx 0.6.8.
Cheers,
Diego

El 20 jun. 2017 6:41 a. m., "Marco F." <notifications@github.com> escribió:

Hi,
I'm trying kamon-akka with kamon-influxdb (both 0.6.7) with akka 2.4.16 and
I'm getting this error at startup.

What could I be missing?

Uncaught error from thread [kamon-akka.actor.default-dispatcher-4]
shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for
ActorSystem[kamon]
java.lang.NoSuchMethodError:
io.netty.util.internal.PlatformDependent.newAtomicIntegerFieldUpdater(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/concurrent/atomic/AtomicIntegerFieldUpdater;
	at org.asynchttpclient.netty.NettyResponseFuture.<clinit>(NettyResponseFuture.java:52)
	at org.asynchttpclient.netty.request.NettyRequestSender.newNettyResponseFuture(NettyRequestSender.java:311)
	at org.asynchttpclient.netty.request.NettyRequestSender.newNettyRequestAndResponseFuture(NettyRequestSender.java:193)
	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:129)
	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:107)
	at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:216)
	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:184)
	at org.asynchttpclient.BoundRequestBuilder.execute(BoundRequestBuilder.java:35)
	at kamon.influxdb.AsyncHttpClient.post(InfluxDBClient.scala:38)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kamon-io/kamon-influxdb/issues/11>, or mute the thread

**Comment by mfirry** [comment]
Is it on maven central?

**Comment by dpsoft** [comment]
@mfirry sorry I got confused with kamon-datadog :(. Can you check if exists more than one version of netty in your classpath?

**Comment by mfirry** [comment]
I can only raelly see `io.netty:netty:4.1.8.Final`

**Comment by mfirry** [comment]
I only really see `io.netty:netty:3.10.6.Final`

**Comment by phamtrinli** [comment]
Hi,

I think the dependency to asyncHttpClient 2.0.24 will cause this error. When including the current version 2.0.35 this error disappeared in my build.

Regards,
Christian

**Comment by vsuharnikov** [comment]
@phamtrinli is right. A fix in your repository (not in `kamon-influxdb`!) for this could be:
```
libraryDependencies += Seq(
  "org.asynchttpclient" % "async-http-client" % "2.1.0-alpha22",
  "io.kamon" %% "kamon-influxdb" % "0.6.8" exclude("org.asynchttpclient", "async-http-client")
)
```
